version: '3'
services:
  server:
    image: 910065472624.dkr.ecr.eu-west-3.amazonaws.com/pumapoc_server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
      - PGHOST=postgres
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_puma_poc
      - PGPORT=5432
      - BACKEND_HOST=http://developers.pumapay.io:8080/
    depends_on:
      - postgres
    networks:
      - puma_poc
    command: sh -c "npm start"

  # Web client
  client:
    image: 910065472624.dkr.ecr.eu-west-3.amazonaws.com/pumapoc_client
    ports:
      - "4200:4200"
      - "49153:49153"
    command: bash -c 'ng lint && ng serve --host 0.0.0.0 --poll 1000'
    networks:
      - puma_poc

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: local_pass
      POSTGRES_USER: local_user
      POSTGRES_DB: local_puma_poc
    ports:
      - "5432:5432"
    volumes:
      - ./db/init-tables.sql:/docker-entrypoint-initdb.d/20-create-tables.sql
      - ./db/insert-users.sql:/docker-entrypoint-initdb.d/21-insert-users.sql
      - ./db/insert-items.sql:/docker-entrypoint-initdb.d/22-insert-items.sql
    networks:
      - puma_poc
    restart: unless-stopped
networks:
  puma_poc:
    driver: bridge
