openapi: 3.0.0
info:
  title: PumaPay PoC API
  version: 0.0.1
  contact:
    name: PumaPay Team
    email: dev@pumapay.io
servers:
  - url: 'http://localhost:8080/api/v1'
    description: Local server
  - url: 'http://developers.pumapay.io:8080/api/v1'
    description: Test server
  
paths:
  /login:
    post:
      summary: User can login to the web app
      operationId: login
      tags: 
        - UserLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties: 
                username:
                  type: string
                password:
                  type: string
      responses:
        '200': 
          description: A Success Response with a JSON object with the user details and the token
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/LoginResponse'
                  - type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
  /items:
    get:
      summary: List all items
      operationId: getAllItems
      tags:
        - Item
      responses:
        '200':
          description: A Success Responce with a JSON array of all items
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Item'
  /items/{itemID}:
    get:
      summary: Get item details based on ID
      operationId: getItemByID
      tags: 
        - Item
      parameters: 
      - name: "itemID"
        in: path
        schema:
          type: string
        description: ID of item details to be returned
        required: true
      responses:
        '200': 
          description: A Success Response with a JSON object with the details of the item
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Item'
  /packages:
    get:
      summary: List all the credit packages
      operationId: getAllPackages
      tags:
        - CreditPackage
      security:
        - TokenAuth: []
      responses:
        '200':
          description: A Success Responce with a JSON array of all the credit packages
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CreditPackage'
  /packages/{packageID}:
    get:
      summary: Get credit package details based on ID
      operationId: getPackageByID
      tags: 
        - CreditPackage
      parameters: 
      - name: "packageID"
        in: path
        schema:
          type: string
        description: ID of credit package to be returned
        required: true
      security:
        - TokenAuth: []
      responses:
        '200': 
          description: A Success Response with a JSON object with the details of the credit package
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CreditPackage'
  /transaction/init:
    get:
      summary: Initiate Transaction with SessionID
      operationId: initiateTransactionWithSessionID
      tags:
        - Transactions
      responses:
        '200':
          description: A success response with a JSON object with the details of the initated transaction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Session'
  /transaction/txStatus/txhash/{transactionHash}:                        
    get:
      summary: Retrieve transaction status
      operationId: retrieveTransactionStatus
      tags:
        - Transactions
      parameters:
        - name: "transactionHash"
          in: path
          schema:
            type: string
          description: Current transaction hash 
          required: true
      responses:
        '200':
          description: Successfully returns the status of the transaction using the transactionHash
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/TransactionLog'
  /transaction/item/tx/{sessionID}/{itemID}:
    get:
      summary: Retrieve transaction data for item with session ID
      operationId: retrieveTransactionDataForItemWithSessionID
      tags:
        - ItemTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema:
          type: string
        description: Current sessionID
        required: true
      - name: "itemID"
        in: path
        schema:
          type: string
        description: ID
         of items details to be returned
        required: true
      responses:
        '200':
          description: Succesfully returns transacation data for item
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Transaction'
  /transaction/item/tx/plain/{sessionID}/{itemID}:
    get:
      summary: Retrieve transaction data for item with session ID
      operationId: retrieveTransactionDataForItemWithSessionID
      tags:
        - ItemTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema:
          type: string
        description: Current sessionID
        required: true
      - name: "itemID"
        in: path
        schema:
          type: string
        description: ID of items details to be returned
        required: true
      responses:
        '200':
          description: Succesfully returns transacation data for item
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Transaction'
  /transaction/item/txStatus/session/{sessionID}:
    get:
      summary: Retrieve item transaction status for session ID
      operationId: getItemTxStatusForSessionID
      tags:
        - ItemTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema: 
          type: string
        description: Current sessionID
        required: true
      - name: txHash
        in: query
        schema:
          type: string
        description: The txHash of the transaction
        required: false
      - name: status 
        in: query
        schema:
          type: integer
        description: The status of the transaction (initiated = -1, scanned = 0, open = 1, approved = 2, declined = 3, cancelled = 4)
        required: true
      - name: fromApp
        in: query
        schema:
          type: integer
        description: Indicates if the transaction came from the wallet app
        required: true
      responses:
        '200':
          description: Succesfully returns the status of the transaction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Session'
  /transaction/package/tx/{sessionID}/{packageID}:
    get:
      summary: Retrieve transaction data for credit package with session ID
      operationId: retrieveTransactionDataForPackageWithSessionID
      tags:
        - CreditPackageTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema:
          type: string
        description: Current session ID
        required: true
      - name: "packageID"
        in: path
        schema:
          type: string
        description: ID of credit packages details to be returned
        required: true
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Succesfully returns transacation data for credit package
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Transaction'
  /transaction/package/tx/plain/{sessionID}/{packageID}:
    get:
      summary: Retrieve transaction data for credit package with session ID
      operationId: retrieveTransactionForPackageWithSessionID
      tags:
        - CreditPackageTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema:
          type: string
        description: Current sessionID
        required: true
      - name: "packageID"
        in: path
        schema:
          type: string
        description: ID of credit packages details to be returned
        required: true
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Succesfully returns transacation data for credit package
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Transaction'
  /transaction/package/txStatus/{packageID}/{userID}/session/{sessionID}:
    get:
      summary: Retrieve transaction status for session of user ID with package ID 
      operationId: getTxStatusForSessionIDOfUserWithPackageID
      tags:
        - CreditPackageTransaction
      parameters:
      - name: "sessionID"
        in: path
        schema: 
          type: string
        description: Current sessionID
        required: true
      - name: "userID"
        in: path
        schema:
          type: string
        description: ID of user for which the credits will be added
        required: true
      - name: "packageID"
        in: path
        schema:
          type: string
        description: ID of the selected credit package
        required: true
      - name: txHash
        in: query
        schema:
          type: string
        description: The txHash of the transaction
        required: false
      - name: status 
        in: query
        schema:
          type: integer
        description: The status of the transaction (initiated = -1, scanned = 0, open = 1, approved = 2, declined = 3, cancelled = 4)
        required: true
      - name: fromApp
        in: query
        schema:
          type: integer
        description: Indicates if the transaction came from the wallet app
        required: true
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Succesfully returns the status of the transaction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Session'
  /rate:
    get:
      summary: Retrieve the rate
      operationId: getRate
      tags:
        - Rate
      responses:
        '200':
          description: A Success Responce with a JSON array of the rate
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      rate:
                        type: number
  /account/{userID}:
    get:
      summary: Retrieve the account details of user
      operationId: retrieveAccountDetailsOfUser
      tags:
        - AccountDetails
      parameters:
      - name: "userID"
        in: path
        schema:
          type: string
        description: Current logged in userID
        required: true
      security:
        - TokenAuth: []
      responses:
        '200':
          description: Succesfully returns account details for logged in user
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AccountResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Account'
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: x-access-token
  schemas:
    Response:
      type: object
      properties:
        success:
          type: boolean
        status:
          type: string
        message:
          type: string
        sessionID:
          type: string
        data:
          type: array
          items: {}
        errcode:
          type: string
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
        status:
          type: string
        message:
          type: string
        token:
          type: string
        user:
          type: string
    AccountResponse:
      type: object
      properties:
        success:
          type: boolean
        status:
          type: string
        message:
          type: string
        data:
          type: array
          items: {}
        errcode:
          type: string
    Item:
      type: object
      properties:
        itemID:
          type: string
        ownerID:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        size:
          type: number
        licence:
          type: string
        itemUrl:
          type: string
        tags:
          type: array
          items:
            type: string
        rating:
          type: array
          items:
            type: number
        uploadedDate:
          type: number
    Session:
      type: object
      properties:
        sessionID:
          type: string
        txHash:
          type: string
        status:
          type: number
        fromPumaWallet:
          type: boolean
    Transaction:
      type: object
      properties:
        callback:
          type: string
        description:
          type: string
        name:
          type: string
        networkid:
          type: number
        to:
          type: string
        value:
          type: number
        signature:
          type: string
    TransactionLog:
      type: object
      properties:
        address:
          type: string
        data:
          type: string
        topics:
          type: array
          items:
            type: string
        logIndex:
          type: string
        transactionIndex:
          type: number
        transactionHash:
          type: string
        blockHash:
          type: string
        blockNumber:
          type: number
    CreditPackage:
      type: object
      properties:
        packageID:
          type: number
        ownerID:
          type: string
        amount:
          type: string
        bonusCredits:
          type: number
        bonusTickets:
          type: number
        featured:
          type: boolean
        priceInUSD:
          type: number
        description:
          type: string
        title:
          type: string
    User:
      type: object
      properties:
        userID:
          type: string
        userName:
          type: string
        email:
          type: string
        salt:
          type: string
        hash:
          type: string
        credits:
          type: integer
        registrationDate:
          type: integer
        walletAddress:
          type: string
    Account:
      type: object
      properties:
        ownerID:
          type: string
        date:
          type: number
        paymentMethod:
          type: string
        totalTime:
          type: number
        changePerMinute:
          type: number
        discountPerMinute:
          type: number
        totalCharged:
          type: number
        totalCredited:
          type: string
        transactionID:
          type: string